# Adapted from https://joshrotenberg.com/mdbook-lint/ci-vs-preprocessor.html#integration-approaches

name: mdbook-lint
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install and run mdbook-lint
        run: |
          cargo install mdbook-lint
          mdbook-lint lint ./ --fail-on-warnings
